name: GH Actions demo
on:
  push:
    branches: [main]
    paths-ignore: [./github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch: 

jobs:
      Build:
        runs-on: ubuntu-latest
        steps: 
          - run: |
              echo " the job was triggered "
              echo " the names of yor branch is ${{ github.ref }} "
          
          - uses: actions/checkout@v3.3.0

          - name: List files in the repository
            run: |
                 echo "The repository ${{ github.repository }} contains the following files:"
                 tree 
    
